
project_id = "wmoylybbwikkqbxiqwbq"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.whatsapp-manager]
verify_jwt = true

# Public proxy with CORS for keepAlive
[functions.proxy]
verify_jwt = false
