project_id = "iqpldxwwvnlloefqfhoo"

[functions]
  [functions.abacate-webhook]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.secure-signup]
    verify_jwt = false
  [functions.secure-login]
    verify_jwt = false
