
project_id = "wmoylybbwikkqbxiqwbq"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

# DEPRECATED - Use whatsapp-cloud-api instead
[functions.whatsapp-manager]
verify_jwt = true

# WhatsApp Cloud API - New implementation
[functions.whatsapp-cloud-api]
verify_jwt = true

# WhatsApp Webhook - Receives events from Meta
[functions.whatsapp-webhook]
verify_jwt = false

# Public proxy with CORS for keepAlive
[functions.proxy]
verify_jwt = false

# WhatsApp WPPConnect session management (must require JWT)
[functions.sessao-de-whatsapp]
verify_jwt = true

